#!/bin/bash

ARTIFACTORY_URL="<REPLACE_ME>"

# Function to calculate the SHA256 checksum of a file
function calculate_sha256() {
  local file="$1"
  local checksum
  checksum=$(shasum -a 256 "$file" | awk '{print $1}')
  echo "$checksum"
}

# Function to check if a file exists and is of a certain type
function is_file_type() {
  if [ -$1 "$2" ]; then
    return 0
  else
    return 1
  fi
}

# Function to remove the tar file created for directories
function remove_tar_file() {
  local tar_file="$1"
  echo "[i] Deleting tar file..."
  rm -f "$tar_file"
}

# Function to encode the original filename to avoid special characters in string
function urlencode() {
    python3 -c "import sys, urllib.parse as ul; print(ul.quote_plus(sys.argv[1]))" "$1"
}

# Function to remove special characters from a given file path's filename string.
remove_special_chars() {
    # Check if a file path is provided
    if [ -z "$1" ]; then
        echo "$1"
    fi

    # Get the file path and separate the directory path and the file name
    filepath="$1"
    dirpath=$(dirname "$filepath")
    filename=$(basename "$filepath")

    # Remove special characters from the file name
    modified_filename=$(echo "$filename" | sed 's/[^a-zA-Z0-9._-]//g')

    # Check if the file name has changed after removing special characters
    if [ "$filename" != "$modified_filename" ]; then
        new_filepath="${dirpath}/${modified_filename}"
        mv "$filepath" "$new_filepath"
        echo "$new_filepath"
    else
        echo "$filepath"
    fi
}

# Check for target file and repository arguments
if [ $# -ne 2 ]; then
  echo "Usage: $0 <TARGET_PATH> <REPO>"
  echo "Available REPO's:"
  echo "----------------------"
  echo "'vm' --> VM ISO, OVF, etc"
  echo "'vt' --> VM Template"
  echo "'vb' --> VM Backup"
  echo "'b' --> Binary"
  echo "'d' --> Docker"
  echo "'db' --> Docker Backup"
  echo "'a' --> Audio"
  echo "'doc' --> DOC"
  echo "'pdf' --> PDF"
  echo "'f' --> Funny"
  echo "'g' --> Games"
  echo "'o' --> Other"
  exit 1
fi

RATE_LIMIT="50M"
TARGET_PATH="$1"
FULL_FILEPATH=$(readlink -f "$TARGET_PATH")
REPO="$2"

# Check if target path is a valid file or directory
if ! is_file_type f "$TARGET_PATH" && ! is_file_type d "$TARGET_PATH"; then
  if [ ! -e "$TARGET_PATH" ]; then
    echo "[!] Error: Target path does not exist"
  else
    echo "[!] Error: Target path is neither a file nor a directory"
  fi
  echo "TARGET_PATH: $TARGET_PATH"
  exit 1
fi

REMOTE_NAME=$(basename "$TARGET_PATH" | urlencode)

# Check for required environment variables and prompt for input if missing
if [ -z "$ARTIFACTORY_USERNAME" ]; then
  read -rp "Enter your username: " ARTIFACTORY_USERNAME
fi

if [ -z "$ARTIFACTORY_PASSWORD" ]; then
  read -rsp "Enter your password: " ARTIFACTORY_PASSWORD
  echo "[i] Consider adding the following lines to either your ~/.bashrc or ~/.profile files:"
  echo "export ARTIFACTORY_USERNAME=\"$ARTIFACTORY_USERNAME\""
  echo "export ARTIFACTORY_PASSWORD=\"$ARTIFACTORY_PASSWORD\""
  echo "[+] Continuing..."
fi

case "$REPO" in
  vm)
    ARTIFACTORY_URL="http://$ARTIFACTORY_URL:8082/artifactory/vm/"
    ;;
  vt)
    ARTIFACTORY_URL="http://$ARTIFACTORY_URL:8082/artifactory/vm_template/"
    ;;
  vb)
    ARTIFACTORY_URL="http://$ARTIFACTORY_URL:8082/artifactory/vm_backup/"
    ;;
  b)
    ARTIFACTORY_URL="http://$ARTIFACTORY_URL:8082/artifactory/binary/"
    ;;
  d)
    ARTIFACTORY_URL="http://$ARTIFACTORY_URL:8082/artifactory/docker/"
    ;;
  db)
    ARTIFACTORY_URL="http://$ARTIFACTORY_URL:8082/artifactory/docker_backup/"
    ;;
  a)
    ARTIFACTORY_URL="http://$ARTIFACTORY_URL:8082/artifactory/audio/"
    ;;
  m)
    ARTIFACTORY_URL="http://$ARTIFACTORY_URL:8082/artifactory/audio/"
    ;;
  doc)
    ARTIFACTORY_URL="http://$ARTIFACTORY_URL:8082/artifactory/documents/"
    ;;
  pdf)
    ARTIFACTORY_URL="http://$ARTIFACTORY_URL:8082/artifactory/pdf/"
    ;;
  f)
    ARTIFACTORY_URL="http://$ARTIFACTORY_URL:8082/artifactory/funny/"
    ;;
  g)
    ARTIFACTORY_URL="http://$ARTIFACTORY_URL:8082/artifactory/games/"
    ;;
  o)
    ARTIFACTORY_URL="http://$ARTIFACTORY_URL:8082/artifactory/other/"
    ;;
  *)
    echo "Error: Invalid repository specified"
    exit 1
    ;;
esac

TARGET_PATH=$(remove_special_chars "$FULL_FILEPATH")

# Upload the file or directory to Artifactory with a progress bar
if is_file_type f "$TARGET_PATH"; then
  # Upload a file to Artifactory
  upload_response=$(curl -s --progress-bar --limit-rate $RATE_LIMIT -T "$TARGET_PATH" -u"$ARTIFACTORY_USERNAME:$ARTIFACTORY_PASSWORD" "${ARTIFACTORY_URL}${REMOTE_NAME}")
echo "$upload_response"
  echo ""

  # Calculate local and remote file checksums
  local_checksum=$(calculate_sha256 "$TARGET_PATH")
  remote_checksum=$(echo "$upload_response" | sed -n 's/.*"sha256"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p')
  remote_checksum="${remote_checksum:0:64}"

  # Compare the checksums and delete the local file if they match
  if [[ "$local_checksum" == "$remote_checksum" ]]; then
    echo "[i] Checksums match. Deployment successful."
    echo "[i] Deleting local file..."
    rm -rf "$TARGET_PATH"
  else
    echo "[!] Error: Checksums do not match. Deployment may have failed."
  fi

else
  echo "[!] Not an individual file, attempting to TAR it..."
  TARGET_PATH=$(echo "$TARGET_PATH" | sed 's/\s*$//')
  REMOTE_NAME=$(basename "$TARGET_PATH")
  if [ -d "$TARGET_PATH" ]; then
    PARENT_DIR=$(dirname "$TARGET_PATH")
    CURRENT_DIR=$(pwd)
    REMOTE_NAME="${REMOTE_NAME}.tar"
    cd "$PARENT_DIR" || exit
    tar -cvf "${REMOTE_NAME}" "$(basename "$TARGET_PATH")"
    cd "$CURRENT_DIR" || exit
  fi
  ENCODED_REMOTE_NAME=$(urlencode "$REMOTE_NAME")
  echo "[i] Tar Complete, now deploying to ${ARTIFACTORY_URL}${ENCODED_REMOTE_NAME}..."
  curl --progress-bar --limit-rate $RATE_LIMIT -T "$REMOTE_NAME" -u"$ARTIFACTORY_USERNAME:$ARTIFACTORY_PASSWORD" "${ARTIFACTORY_URL}${ENCODED_REMOTE_NAME}"
  echo ""

  # Calculate local and remote file checksums
  local_checksum=$(calculate_sha256 "$TARGET_PATH")
  remote_checksum=$(echo "$upload_response" | sed -n 's/.*"sha256"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p')
  remote_checksum="${remote_checksum:0:64}"

  # Compare the checksums and delete the tar file if they match
  if [ "$local_tar_checksum" == "$remote_tar_checksum" ]; then
    echo "[i] Checksums match. Deployment successful."
    remove_tar_file "$REMOTE_NAME"
    rm -rf "$TARGET_PATH"
  else
    echo "[!] Error: Checksums do not match. Deployment may have failed."
  fi
fi
